name: Elixir CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10-slim
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run linter
      run: mix credo
    - name: Run Tests
      run: mix coveralls.html --trace
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cover/excoveralls.html
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        output-file: 'CHANGELOG.md'
        changelog-release-count: 0
