name: ElixirCI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run linter
      run: mix credo
    - name: Run Tests
      run: mix test --trace
  code_coverage:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10-slim
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run code coverage
      run: mix coveralls.github
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cover/excoveralls.html
  #release:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v1
  #  - name: Setup Node.js
  #    uses: actions/setup-node@v1
  #    with:
  #      node-version: 12
  #  - name: Release
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    run: |
  #      npx semantic-release@17
  #      npx uninstall @semantic-release/npm
